# Generated by Django 4.0.10 on 2024-03-30 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NutriPapiApp', '0004_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('meal_type', models.CharField(max_length=100, verbose_name='Meal Type')),
                ('calories', models.IntegerField(verbose_name='Calories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
