# Generated by Django 4.0.10 on 2024-03-30 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NutriPapiApp', '0006_meallog_breakfast_calories_meallog_dinner_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meallog',
            name='meal_type',
        ),
    ]
