# Generated by Django 4.0.10 on 2024-04-02 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriPapiApp', '0007_remove_meallog_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encrypted_birthday',
            field=models.BinaryField(blank=True, null=True, verbose_name='Encrypted Birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_email',
            field=models.BinaryField(blank=True, null=True, verbose_name='Encrypted Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_height',
            field=models.BinaryField(blank=True, null=True, verbose_name='Encrypted Height'),
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_weight',
            field=models.BinaryField(blank=True, null=True, verbose_name='Encrypted Weight'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weekly_physical_activity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Weekly Physical Activity in hours'),
        ),
    ]
