# Generated by Django 4.0.10 on 2024-04-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriPapiApp', '0008_user_encrypted_birthday_user_encrypted_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, verbose_name='Failed Login Attempts'),
        ),
        migrations.AddField(
            model_name='user',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lockout Until'),
        ),
    ]
