# Generated by Django 4.0.10 on 2024-04-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriPapiApp', '0009_user_failed_login_attempts_user_lockout_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='nutritional_information',
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(blank=True, null=True, verbose_name='Calories'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutritional_information',
            field=models.TextField(blank=True, null=True, verbose_name='Nutritional Information'),
        ),
    ]
