# Generated by Django 4.0.10 on 2024-04-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriPapiApp', '0010_remove_ingredient_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='nutritional_information',
            field=models.TextField(blank=True, null=True, verbose_name='Nutritional Information'),
        ),
    ]
