# Generated by Django 4.0.10 on 2024-04-03 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NutriPapiApp', '0010_remove_ingredient_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date_and_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='recipes',
        ),
        migrations.AddField(
            model_name='schedule',
            name='breakfast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakfast_schedules', to='NutriPapiApp.recipe'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner_schedules', to='NutriPapiApp.recipe'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunch_schedules', to='NutriPapiApp.recipe'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
