Feature: Automated Meal Plan Categorization
  As a NutriPapi user,
  I want the system to categorize my meal plans into breakfast, lunch, dinner, and snacks
  so that I can have a structured and balanced daily eating schedule.

Scenario: Automated Meal Categorization upon Creation (Normal Flow)
Given the user has logged into the NutriPapi system and updated their health information page,
When they choose to view the meal suggestions generated by the system,
Then the system automatically categorizes the meals based on the time of day and nutritional content, placing them into breakfast, lunch, dinner, or snack categories in the user's daily meal plan.

Scenario: Editing Meal Categories (Alternate Flow)
Given the user is reviewing their daily meal plan in the NutriPapi system,
When they decide to customize the meal categories for specific meals,
Then the system allows the user to manually change the meal type category (e.g., from lunch to dinner), providing flexibility in organizing their meal plan according to their preferences.

Scenario: Invalid Meal Categorization (Error Flow)
Given the user is inputting or editing a meal in their NutriPapi meal plan,
When they attempt to specify an invalid meal type category or leave it unspecified,
Then the system displays an error message indicating that the meal categorization is required and prompts the user to select a valid meal type category from the available options (breakfast, lunch, dinner, snack).