name: Django CI

on:
  push:
    paths: 
      - 'Backend/**'

permissions:
    checks: write

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./Backend
    - name: Run Tests
      run: |
        python manage.py behave --junit --junit-directory ./test-reports || true
      working-directory: ./Backend
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: './Backend/test-reports/*.xml'
